title: Settings
data:
  site_name: 'Troy Pavlek'
  social:
    -
      id: me1xcwky
      name: Instagram
      url: 'https://www.instagram.com/troypavlek'
      icon: site/social-icons/instagram.svg
    -
      id: AosUmbVH
      name: Twitter
      url: 'https://twitter.com/troypavlek'
      icon: site/social-icons/twitter.svg
    -
      id: O5vmdsVL
      name: Email
      url: 'mailto:troy@tpavlek.me'
      icon: site/social-icons/email.svg
    -
      id: me1xdfff
      name: YouTube
      url: 'https://www.youtube.com/@troypavlek'
      icon: site/social-icons/youtube.svg
