title: Settings
data:
  site_name: 'Troy Pavlek'
  social:
    -
      id: AosUmbVH
      name: Twitter
      url: 'https://twitter.com/troypavlek'
      icon: site/social-icons/twitter.svg
    -
      id: O5vmdsVL
      name: Email
      url: 'mailto:troy@tpavlek.me'
      icon: site/social-icons/email.svg
