title: Update
content: 'Updates about new candidates running, changing information or dropping out.'
updated_by: 9c6b6866-e047-4568-b3f4-71623caf17dd
updated_at: 1737226797
blueprint: yegvote_2025_update_type
